"""Generate the fixed-arity, struct-layout-preserving Core tuple header."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


DEFAULT_MAX_ARITY = 32
LAYOUT_BEGIN = "// BEGIN GENERATED TUPLE LAYOUTS"
LAYOUT_END = "// END GENERATED TUPLE LAYOUTS"
GET_BEGIN = "    // BEGIN GENERATED TUPLE GET BRANCHES"
GET_END = "    // END GENERATED TUPLE GET BRANCHES"


def type_parameters(arity: int) -> str:
    return ", ".join(f"typename T{index}" for index in range(arity))


def type_arguments(arity: int) -> str:
    return ", ".join(f"T{index}" for index in range(arity))


def layout_members(arity: int) -> str:
    return " ".join(f"T{index} value{index}_;" for index in range(arity))


def generate_layouts(max_arity: int) -> str:
    lines = ["template<>", "struct tuple_layout<> {};", ""]
    for arity in range(1, max_arity + 1):
        if arity > 1:
            lines.extend([f"template<{type_parameters(arity)}>",
                          f"struct tuple_layout<{type_arguments(arity)}> {{ {layout_members(arity)} }};", ""])
        else:
            lines.extend(["template<typename T0>", "struct tuple_layout<T0> { T0 value0_; };", ""])
    return "\n".join(lines).rstrip()


def generate_get_branches(max_arity: int) -> str:
    lines = []
    for index in range(max_arity - 1):
        keyword = "if" if index == 0 else "else if"
        lines.append(f"    {keyword} constexpr (I == {index}u) return (value.storage_.value{index}_);")
    lines.append(f"    else return (value.storage_.value{max_arity - 1}_);")
    return "\n".join(lines)


def replace_region(content: str, begin: str, end: str, replacement: str,
                   legacy_begin: str | None = None, legacy_end: str | None = None) -> str:
    begin_index = content.find(begin)
    if begin_index >= 0:
        end_index = content.find(end, begin_index)
        if end_index < 0:
            raise ValueError(f"missing generated region terminator: {end}")
        return content[:begin_index] + begin + "\n" + replacement + "\n" + end + content[end_index + len(end):]

    if legacy_begin is None or legacy_end is None:
        raise ValueError(f"missing generated region: {begin}")
    begin_index = content.find(legacy_begin)
    end_index = content.find(legacy_end, begin_index)
    if begin_index < 0 or end_index < 0:
        raise ValueError(f"missing legacy generated region: {legacy_begin}")
    return content[:begin_index] + begin + "\n" + replacement + "\n" + end + "\n\n" + content[end_index:]


def replace_get_branches(content: str, signature: str, max_arity: int) -> str:
    signature_index = content.find(signature)
    if signature_index < 0:
        raise ValueError(f"missing tuple get overload: {signature}")
    body_start = signature_index + len(signature)
    begin_index = content.find(GET_BEGIN, body_start)
    if begin_index >= 0:
        end_index = content.find(GET_END, begin_index)
        if end_index < 0:
            raise ValueError("missing tuple get generated region terminator")
        return content[:begin_index] + GET_BEGIN + "\n" + generate_get_branches(max_arity) + "\n" + GET_END + content[end_index + len(GET_END):]

    branch_start = content.find("    if constexpr (I == 0u)", body_start)
    body_end = content.find("\n}", branch_start)
    if branch_start < 0 or body_end < 0:
        raise ValueError("missing legacy tuple get branches")
    return content[:branch_start] + GET_BEGIN + "\n" + generate_get_branches(max_arity) + "\n" + GET_END + content[body_end:]


def generate_header(content: str, max_arity: int) -> str:
    if max_arity == 0:
        raise ValueError("max arity must be positive")

    generated_comment = "// Generated by generate_tuple.py; do not edit generated regions manually.\n"
    if generated_comment not in content:
        content = content.replace("#pragma once\n", "#pragma once\n\n" + generated_comment, 1)

    content = replace_region(
        content, LAYOUT_BEGIN, LAYOUT_END, generate_layouts(max_arity),
        "template<>\nstruct tuple_layout<> {};",
        "template<typename T, typename... Ts>\ninline constexpr size_t tuple_type_count_v")
    content = re.sub(
        r"static_assert\(sizeof\.\.\.\(Ts\) <= \d+u, \"horizon::core::tuple supports at most [^\"]+\"\);",
        f"static_assert(sizeof...(Ts) <= {max_arity}u, \"horizon::core::tuple supports at most {max_arity} elements\");",
        content,
        count=1)
    content = replace_get_branches(content, "constexpr decltype(auto) get(tuple<Ts...> &value) noexcept {\n", max_arity)
    content = replace_get_branches(content, "constexpr decltype(auto) get(const tuple<Ts...> &value) noexcept {\n", max_arity)
    return content


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-arity", type=int, default=DEFAULT_MAX_ARITY,
                        help=f"maximum tuple arity to generate (default: {DEFAULT_MAX_ARITY})")
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("tuple.h"),
                        help="tuple header to generate")
    parser.add_argument("--check", action="store_true",
                        help="fail when the output file is not generated with these options")
    arguments = parser.parse_args()

    if arguments.max_arity <= 0:
        parser.error("--max-arity must be positive")

    original = arguments.output.read_text(encoding="utf-8")
    generated = generate_header(original, arguments.max_arity)
    if arguments.check:
        return 0 if generated == original else 1
    arguments.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
