#pragma once

// Generated by generate_tuple.py; do not edit generated regions manually.

#include <compare>
#include <cstddef>
#include <functional>
#include <tuple>
#include <type_traits>
#include <utility>

namespace horizon::core {

template<typename... Ts>
class tuple;

template<typename T>
struct tuple_size;

template<size_t I, typename T>
struct tuple_element;

template<size_t I, typename... Ts>
constexpr decltype(auto) get(tuple<Ts...> &value) noexcept;

template<size_t I, typename... Ts>
constexpr decltype(auto) get(const tuple<Ts...> &value) noexcept;

template<size_t I, typename... Ts>
constexpr decltype(auto) get(tuple<Ts...> &&value) noexcept;

template<size_t I, typename... Ts>
constexpr decltype(auto) get(const tuple<Ts...> &&value) noexcept;

namespace detail {

template<typename... Ts>
struct tuple_layout;

// BEGIN GENERATED TUPLE LAYOUTS
template<>
struct tuple_layout<> {};

template<typename T0>
struct tuple_layout<T0> { T0 value0_; };

template<typename T0, typename T1>
struct tuple_layout<T0, T1> { T0 value0_; T1 value1_; };

template<typename T0, typename T1, typename T2>
struct tuple_layout<T0, T1, T2> { T0 value0_; T1 value1_; T2 value2_; };

template<typename T0, typename T1, typename T2, typename T3>
struct tuple_layout<T0, T1, T2, T3> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4>
struct tuple_layout<T0, T1, T2, T3, T4> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5>
struct tuple_layout<T0, T1, T2, T3, T4, T5> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; T25 value25_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; T25 value25_; T26 value26_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; T25 value25_; T26 value26_; T27 value27_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; T25 value25_; T26 value26_; T27 value27_; T28 value28_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; T25 value25_; T26 value26_; T27 value27_; T28 value28_; T29 value29_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; T25 value25_; T26 value26_; T27 value27_; T28 value28_; T29 value29_; T30 value30_; };

template<typename T0, typename T1, typename T2, typename T3, typename T4, typename T5, typename T6, typename T7, typename T8, typename T9, typename T10, typename T11, typename T12, typename T13, typename T14, typename T15, typename T16, typename T17, typename T18, typename T19, typename T20, typename T21, typename T22, typename T23, typename T24, typename T25, typename T26, typename T27, typename T28, typename T29, typename T30, typename T31>
struct tuple_layout<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22, T23, T24, T25, T26, T27, T28, T29, T30, T31> { T0 value0_; T1 value1_; T2 value2_; T3 value3_; T4 value4_; T5 value5_; T6 value6_; T7 value7_; T8 value8_; T9 value9_; T10 value10_; T11 value11_; T12 value12_; T13 value13_; T14 value14_; T15 value15_; T16 value16_; T17 value17_; T18 value18_; T19 value19_; T20 value20_; T21 value21_; T22 value22_; T23 value23_; T24 value24_; T25 value25_; T26 value26_; T27 value27_; T28 value28_; T29 value29_; T30 value30_; T31 value31_; };
// END GENERATED TUPLE LAYOUTS

template<typename T, typename... Ts>
inline constexpr size_t tuple_type_count_v = (size_t{0} + ... + (std::is_same_v<T, Ts> ? 1u : 0u));

template<typename T, typename... Ts>
struct tuple_type_index;

template<typename T, typename First, typename... Rest>
struct tuple_type_index<T, First, Rest...> {
    static constexpr size_t value = std::is_same_v<T, First> ? 0u : 1u + tuple_type_index<T, Rest...>::value;
};

template<typename T>
struct tuple_type_index<T> {
    static constexpr size_t value = 0u;
};

template<typename Function, typename Tuple, size_t... I>
constexpr decltype(auto) apply_impl(Function &&function, Tuple &&value, std::index_sequence<I...>) {
    return std::invoke(std::forward<Function>(function), get<I>(std::forward<Tuple>(value))...);
}

template<typename Tuple, size_t... I>
constexpr auto tuple_copy_impl(Tuple &&value, std::index_sequence<I...>) {
    return tuple{get<I>(std::forward<Tuple>(value))...};
}

template<typename Left, typename Right, size_t... I, size_t... J>
constexpr auto tuple_cat_two_impl(Left &&left, Right &&right,
                                  std::index_sequence<I...>, std::index_sequence<J...>) {
    return tuple{get<I>(std::forward<Left>(left))..., get<J>(std::forward<Right>(right))...};
}

template<typename Left, typename Right>
constexpr auto tuple_cat_two(Left &&left, Right &&right) {
    using left_type = std::remove_cvref_t<Left>;
    using right_type = std::remove_cvref_t<Right>;
    return tuple_cat_two_impl(std::forward<Left>(left), std::forward<Right>(right),
                              std::make_index_sequence<tuple_size<left_type>::value>{},
                              std::make_index_sequence<tuple_size<right_type>::value>{});
}

template<typename Left, typename Right, size_t... I>
constexpr void swap_impl(Left &left, Right &right, std::index_sequence<I...>) {
    using std::swap;
    (swap(get<I>(left), get<I>(right)), ...);
}

}// namespace detail

template<typename... Ts>
class tuple {
    static_assert(sizeof...(Ts) <= 32u, "horizon::core::tuple supports at most 32 elements");

private:
    detail::tuple_layout<Ts...> storage_;

    template<size_t I, typename... Us>
    friend constexpr decltype(auto) get(tuple<Us...> &value) noexcept;
    template<size_t I, typename... Us>
    friend constexpr decltype(auto) get(const tuple<Us...> &value) noexcept;

public:
    constexpr tuple() requires (std::is_default_constructible_v<Ts> && ...) = default;
    constexpr tuple(const tuple &) = default;
    constexpr tuple(tuple &&) noexcept = default;
    constexpr tuple &operator=(const tuple &) = default;
    constexpr tuple &operator=(tuple &&) noexcept = default;

    template<typename... Us>
    requires(sizeof...(Ts) == sizeof...(Us) && (std::is_constructible_v<Ts, Us &&> && ...))
    constexpr explicit(!(std::is_convertible_v<Us &&, Ts> && ...))
        tuple(Us &&...values) noexcept((std::is_nothrow_constructible_v<Ts, Us &&> && ...))
        : storage_{std::forward<Us>(values)...} {}

    constexpr bool operator==(const tuple &) const = default;
    constexpr auto operator<=>(const tuple &) const = default;
};

template<typename... Ts>
tuple(Ts...) -> tuple<std::unwrap_ref_decay_t<Ts>...>;

template<typename... Ts>
struct tuple_size<tuple<Ts...>> : std::integral_constant<size_t, sizeof...(Ts)> {};

template<typename T>
inline constexpr size_t tuple_size_v = tuple_size<std::remove_cvref_t<T>>::value;

template<size_t I, typename... Ts>
struct tuple_element<I, tuple<Ts...>> {
    static_assert(I < sizeof...(Ts), "tuple element index is out of range");
    using type = std::tuple_element_t<I, std::tuple<Ts...>>;
};

template<size_t I, typename T>
using tuple_element_t = typename tuple_element<I, std::remove_cvref_t<T>>::type;

template<size_t I, typename... Ts>
constexpr decltype(auto) get(tuple<Ts...> &value) noexcept {
    static_assert(I < sizeof...(Ts), "tuple element index is out of range");
    // BEGIN GENERATED TUPLE GET BRANCHES
    if constexpr (I == 0u) return (value.storage_.value0_);
    else if constexpr (I == 1u) return (value.storage_.value1_);
    else if constexpr (I == 2u) return (value.storage_.value2_);
    else if constexpr (I == 3u) return (value.storage_.value3_);
    else if constexpr (I == 4u) return (value.storage_.value4_);
    else if constexpr (I == 5u) return (value.storage_.value5_);
    else if constexpr (I == 6u) return (value.storage_.value6_);
    else if constexpr (I == 7u) return (value.storage_.value7_);
    else if constexpr (I == 8u) return (value.storage_.value8_);
    else if constexpr (I == 9u) return (value.storage_.value9_);
    else if constexpr (I == 10u) return (value.storage_.value10_);
    else if constexpr (I == 11u) return (value.storage_.value11_);
    else if constexpr (I == 12u) return (value.storage_.value12_);
    else if constexpr (I == 13u) return (value.storage_.value13_);
    else if constexpr (I == 14u) return (value.storage_.value14_);
    else if constexpr (I == 15u) return (value.storage_.value15_);
    else if constexpr (I == 16u) return (value.storage_.value16_);
    else if constexpr (I == 17u) return (value.storage_.value17_);
    else if constexpr (I == 18u) return (value.storage_.value18_);
    else if constexpr (I == 19u) return (value.storage_.value19_);
    else if constexpr (I == 20u) return (value.storage_.value20_);
    else if constexpr (I == 21u) return (value.storage_.value21_);
    else if constexpr (I == 22u) return (value.storage_.value22_);
    else if constexpr (I == 23u) return (value.storage_.value23_);
    else if constexpr (I == 24u) return (value.storage_.value24_);
    else if constexpr (I == 25u) return (value.storage_.value25_);
    else if constexpr (I == 26u) return (value.storage_.value26_);
    else if constexpr (I == 27u) return (value.storage_.value27_);
    else if constexpr (I == 28u) return (value.storage_.value28_);
    else if constexpr (I == 29u) return (value.storage_.value29_);
    else if constexpr (I == 30u) return (value.storage_.value30_);
    else return (value.storage_.value31_);
    // END GENERATED TUPLE GET BRANCHES
}

template<size_t I, typename... Ts>
constexpr decltype(auto) get(const tuple<Ts...> &value) noexcept {
    static_assert(I < sizeof...(Ts), "tuple element index is out of range");
    // BEGIN GENERATED TUPLE GET BRANCHES
    if constexpr (I == 0u) return (value.storage_.value0_);
    else if constexpr (I == 1u) return (value.storage_.value1_);
    else if constexpr (I == 2u) return (value.storage_.value2_);
    else if constexpr (I == 3u) return (value.storage_.value3_);
    else if constexpr (I == 4u) return (value.storage_.value4_);
    else if constexpr (I == 5u) return (value.storage_.value5_);
    else if constexpr (I == 6u) return (value.storage_.value6_);
    else if constexpr (I == 7u) return (value.storage_.value7_);
    else if constexpr (I == 8u) return (value.storage_.value8_);
    else if constexpr (I == 9u) return (value.storage_.value9_);
    else if constexpr (I == 10u) return (value.storage_.value10_);
    else if constexpr (I == 11u) return (value.storage_.value11_);
    else if constexpr (I == 12u) return (value.storage_.value12_);
    else if constexpr (I == 13u) return (value.storage_.value13_);
    else if constexpr (I == 14u) return (value.storage_.value14_);
    else if constexpr (I == 15u) return (value.storage_.value15_);
    else if constexpr (I == 16u) return (value.storage_.value16_);
    else if constexpr (I == 17u) return (value.storage_.value17_);
    else if constexpr (I == 18u) return (value.storage_.value18_);
    else if constexpr (I == 19u) return (value.storage_.value19_);
    else if constexpr (I == 20u) return (value.storage_.value20_);
    else if constexpr (I == 21u) return (value.storage_.value21_);
    else if constexpr (I == 22u) return (value.storage_.value22_);
    else if constexpr (I == 23u) return (value.storage_.value23_);
    else if constexpr (I == 24u) return (value.storage_.value24_);
    else if constexpr (I == 25u) return (value.storage_.value25_);
    else if constexpr (I == 26u) return (value.storage_.value26_);
    else if constexpr (I == 27u) return (value.storage_.value27_);
    else if constexpr (I == 28u) return (value.storage_.value28_);
    else if constexpr (I == 29u) return (value.storage_.value29_);
    else if constexpr (I == 30u) return (value.storage_.value30_);
    else return (value.storage_.value31_);
    // END GENERATED TUPLE GET BRANCHES
}

template<size_t I, typename... Ts>
constexpr decltype(auto) get(tuple<Ts...> &&value) noexcept {
    return std::move(get<I>(value));
}

template<size_t I, typename... Ts>
constexpr decltype(auto) get(const tuple<Ts...> &&value) noexcept {
    return std::move(get<I>(value));
}

template<typename T, typename... Ts>
requires(detail::tuple_type_count_v<T, Ts...> == 1u)
constexpr decltype(auto) get(tuple<Ts...> &value) noexcept {
    return get<detail::tuple_type_index<T, Ts...>::value>(value);
}

template<typename T, typename... Ts>
requires(detail::tuple_type_count_v<T, Ts...> == 1u)
constexpr decltype(auto) get(const tuple<Ts...> &value) noexcept {
    return get<detail::tuple_type_index<T, Ts...>::value>(value);
}

template<typename T, typename... Ts>
requires(detail::tuple_type_count_v<T, Ts...> == 1u)
constexpr decltype(auto) get(tuple<Ts...> &&value) noexcept {
    return get<detail::tuple_type_index<T, Ts...>::value>(std::move(value));
}

template<typename T, typename... Ts>
requires(detail::tuple_type_count_v<T, Ts...> == 1u)
constexpr decltype(auto) get(const tuple<Ts...> &&value) noexcept {
    return get<detail::tuple_type_index<T, Ts...>::value>(std::move(value));
}

template<size_t I, typename Tuple>
constexpr decltype(auto) tuple_get(Tuple &&value) noexcept {
    return get<I>(std::forward<Tuple>(value));
}

template<typename... Ts>
constexpr auto make_tuple(Ts &&...values) {
    return tuple<std::unwrap_ref_decay_t<Ts>...>{std::forward<Ts>(values)...};
}

template<typename... Ts>
constexpr auto tie(Ts &...values) noexcept {
    return tuple<Ts &...>{values...};
}

template<typename... Ts>
constexpr auto forward_as_tuple(Ts &&...values) noexcept {
    return tuple<Ts &&...>{std::forward<Ts>(values)...};
}

template<typename Function, typename Tuple>
constexpr decltype(auto) apply(Function &&function, Tuple &&value) {
    return detail::apply_impl(std::forward<Function>(function), std::forward<Tuple>(value),
                              std::make_index_sequence<tuple_size_v<Tuple>>{});
}

constexpr tuple<> tuple_cat() noexcept { return {}; }

template<typename Tuple>
constexpr auto tuple_cat(Tuple &&value) {
    return detail::tuple_copy_impl(std::forward<Tuple>(value),
                                   std::make_index_sequence<tuple_size_v<Tuple>>{});
}

template<typename Left, typename Right>
constexpr auto tuple_cat(Left &&left, Right &&right) {
    return detail::tuple_cat_two(std::forward<Left>(left), std::forward<Right>(right));
}

template<typename Left, typename Right, typename... Rest>
constexpr auto tuple_cat(Left &&left, Right &&right, Rest &&...rest) {
    return tuple_cat(detail::tuple_cat_two(std::forward<Left>(left), std::forward<Right>(right)),
                     std::forward<Rest>(rest)...);
}

template<typename... Ts>
constexpr void swap(tuple<Ts...> &left, tuple<Ts...> &right) {
    detail::swap_impl(left, right, std::make_index_sequence<sizeof...(Ts)>{});
}

}// namespace horizon::core

namespace std {

template<typename... Ts>
struct tuple_size<horizon::core::tuple<Ts...>> : integral_constant<size_t, sizeof...(Ts)> {};

template<size_t I, typename... Ts>
struct tuple_element<I, horizon::core::tuple<Ts...>> {
    using type = horizon::core::tuple_element_t<I, horizon::core::tuple<Ts...>>;
};

}// namespace std
