include_guard(GLOBAL)

function(_horizon_alias_target alias_name)
    if(TARGET ${alias_name})
        return()
    endif()

    foreach(candidate IN LISTS ARGN)
        if(TARGET ${candidate})
            add_library(${alias_name} INTERFACE IMPORTED GLOBAL)
            target_link_libraries(${alias_name} INTERFACE ${candidate})
            return()
        endif()
    endforeach()
endfunction()

function(_horizon_require_target target_name detail)
    if(NOT TARGET ${target_name})
        message(FATAL_ERROR "Required Horizon dependency target '${target_name}' is missing: ${detail}")
    endif()
endfunction()

find_package(ktm CONFIG REQUIRED)
_horizon_alias_target(horizon::ktm ktm::ktm)
_horizon_require_target(horizon::ktm "ktm is included by Horizon public headers")

find_package(pfr CONFIG REQUIRED)
_horizon_alias_target(horizon::pfr pfr::pfr pfr)
_horizon_require_target(horizon::pfr "boost::pfr headers are used by Helicon")

find_package(SPIRV-Tools CONFIG REQUIRED)
_horizon_alias_target(horizon::spirv_tools_link SPIRV-Tools-link spirv-tools::spirv-tools-link)
_horizon_require_target(horizon::spirv_tools_link "SPIRV-Tools link target is required by Helicon")

if(MSVC AND TARGET SPIRV-Tools-opt)
    get_target_property(_horizon_spirv_tools_opt_imported SPIRV-Tools-opt IMPORTED)
endif()
if(MSVC AND TARGET SPIRV-Tools-opt AND NOT _horizon_spirv_tools_opt_imported)
    target_compile_options(SPIRV-Tools-opt PRIVATE /Wv:18)
    target_compile_options(SPIRV-Tools-opt PRIVATE /wd4717 /wd5232)
endif()
unset(_horizon_spirv_tools_opt_imported)

find_package(VulkanHeaders CONFIG REQUIRED)
_horizon_alias_target(horizon::vulkan_headers vulkan-headers::vulkan-headers Vulkan-Headers)
_horizon_require_target(horizon::vulkan_headers "Vulkan headers are required by Horizon and Volk")

find_package(volk CONFIG REQUIRED)
_horizon_alias_target(horizon::volk volk::volk volk)
_horizon_require_target(horizon::volk "Volk is required by the Vulkan backend")

find_package(VulkanMemoryAllocator CONFIG REQUIRED)
_horizon_alias_target(horizon::vma GPUOpen::VulkanMemoryAllocator vulkan-memory-allocator::vulkan-memory-allocator VulkanMemoryAllocator)
_horizon_require_target(horizon::vma "Vulkan Memory Allocator is required by the Vulkan backend")

if(HORIZON_BUILD_OCARINA AND DEFINED ENV{CUDA_PATH})
    find_package(fmt CONFIG REQUIRED)
    find_package(spdlog CONFIG REQUIRED)
    find_package(xxHash CONFIG REQUIRED)
    _horizon_alias_target(horizon::fmt fmt::fmt-header-only fmt::fmt)
    _horizon_alias_target(horizon::spdlog spdlog::spdlog spdlog)
    _horizon_alias_target(horizon::xxhash xxHash::xxhash xxhash::xxhash xxhash)
    _horizon_require_target(horizon::fmt "fmt is required by the Ocarina module")
    _horizon_require_target(horizon::spdlog "spdlog is required by the Ocarina module")
    _horizon_require_target(horizon::xxhash "xxHash is required by the Ocarina module")
endif()
