include_guard(GLOBAL)

function(_horizon_alias_target alias_name)
    if(TARGET ${alias_name})
        return()
    endif()

    foreach(candidate IN LISTS ARGN)
        if(TARGET ${candidate})
            add_library(${alias_name} INTERFACE IMPORTED GLOBAL)
            target_link_libraries(${alias_name} INTERFACE ${candidate})
            return()
        endif()
    endforeach()
endfunction()

function(_horizon_require_target target_name detail)
    if(NOT TARGET ${target_name})
        message(FATAL_ERROR "Required Horizon dependency target '${target_name}' is missing: ${detail}")
    endif()
endfunction()

find_package(quill CONFIG REQUIRED)
_horizon_require_target(quill::quill "Quill is required by Horizon kernel logging")

find_package(fmt CONFIG REQUIRED)
find_package(spdlog CONFIG REQUIRED)
find_package(xxHash CONFIG REQUIRED)
_horizon_alias_target(horizon::fmt fmt::fmt-header-only fmt::fmt)
_horizon_alias_target(horizon::spdlog spdlog::spdlog spdlog)
_horizon_alias_target(horizon::xxhash xxHash::xxhash xxhash::xxhash xxhash)
_horizon_require_target(horizon::fmt "fmt is required by Horizon Core formatting")
_horizon_require_target(horizon::spdlog "spdlog is required by Horizon Core logging")
_horizon_require_target(horizon::xxhash "xxHash is required by Horizon Core hashing")
