#pragma once
#include <Codegen/VariateProxy.h>

namespace EmbeddedShader
{
    template<typename T> requires ktm::is_vector_v<T>
    struct VecProxyMap;

    template<typename Type>
    struct SwizzleProxy : VariateProxy<Type>
    {
        using base_type = VariateProxy<Type>;
        using base_type::operator=;
        typename VecProxyMap<Type>::proxy_type operator->() requires (ktm::is_vector_v<Type>) = delete;

        SwizzleProxy(std::shared_ptr<Ast::Value> parent, std::string name) : base_type(Ast::AST::access(std::move(parent),std::move(name),Ast::AST::createType<Type>()))
        {

        }
    };

#define SWIZZLE_DECLARE(dimension,name) SwizzleProxy<ktm::vec<dimension,T>> name();
#define SWIZZLE_DEFINED(className,dimension,name) template<typename T> SwizzleProxy<ktm::vec<dimension,T>> className<T>::name() { return {this->parent,#name}; }

    template<typename T>
    struct Vec2Proxy
    {
        template<typename Type>
        friend struct VariateProxy;

        using value_type = T;
        static constexpr uint32_t dimension = 2;
        VariateProxy<T> x;
        VariateProxy<T> y;

        SWIZZLE_DECLARE(2, xy)
        SWIZZLE_DECLARE(2, yx)

        SWIZZLE_DECLARE(2, xx)
        SWIZZLE_DECLARE(2, yy)
    protected:
        std::shared_ptr<Ast::Value> parent;
    };

    SWIZZLE_DEFINED(Vec2Proxy,2,xy)
    SWIZZLE_DEFINED(Vec2Proxy,2,yx)

    SWIZZLE_DEFINED(Vec2Proxy,2,xx)
    SWIZZLE_DEFINED(Vec2Proxy,2,yy)

    template<typename T>
    struct Vec3Proxy : Vec2Proxy<T>
    {
        static constexpr uint32_t dimension = 3;
        VariateProxy<T> z;
        SWIZZLE_DECLARE(2, xz)
        SWIZZLE_DECLARE(2, yz)
        SWIZZLE_DECLARE(2, zx)
        SWIZZLE_DECLARE(2, zy)

        SWIZZLE_DECLARE(2, zz)

        SWIZZLE_DECLARE(3, xxx)
        SWIZZLE_DECLARE(3, xxy)
        SWIZZLE_DECLARE(3, xxz)
        SWIZZLE_DECLARE(3, xyx)
        SWIZZLE_DECLARE(3, xyy)
        SWIZZLE_DECLARE(3, xyz)
        SWIZZLE_DECLARE(3, xzx)
        SWIZZLE_DECLARE(3, xzy)
        SWIZZLE_DECLARE(3, xzz)
        SWIZZLE_DECLARE(3, yxx)
        SWIZZLE_DECLARE(3, yxy)
        SWIZZLE_DECLARE(3, yxz)
        SWIZZLE_DECLARE(3, yyx)
        SWIZZLE_DECLARE(3, yyy)
        SWIZZLE_DECLARE(3, yyz)
        SWIZZLE_DECLARE(3, yzx)
        SWIZZLE_DECLARE(3, yzy)
        SWIZZLE_DECLARE(3, yzz)
        SWIZZLE_DECLARE(3, zxx)
        SWIZZLE_DECLARE(3, zxy)
        SWIZZLE_DECLARE(3, zxz)
        SWIZZLE_DECLARE(3, zyx)
        SWIZZLE_DECLARE(3, zyy)
        SWIZZLE_DECLARE(3, zyz)
        SWIZZLE_DECLARE(3, zzx)
        SWIZZLE_DECLARE(3, zzy)
        SWIZZLE_DECLARE(3, zzz)
    };

    SWIZZLE_DEFINED(Vec3Proxy,2, xz)
    SWIZZLE_DEFINED(Vec3Proxy,2, yz)
    SWIZZLE_DEFINED(Vec3Proxy,2, zx)
    SWIZZLE_DEFINED(Vec3Proxy,2, zy)

    SWIZZLE_DEFINED(Vec3Proxy,2, zz)

    SWIZZLE_DEFINED(Vec3Proxy,3, xxx)
    SWIZZLE_DEFINED(Vec3Proxy,3, xxy)
    SWIZZLE_DEFINED(Vec3Proxy,3, xxz)
    SWIZZLE_DEFINED(Vec3Proxy,3, xyx)
    SWIZZLE_DEFINED(Vec3Proxy,3, xyy)
    SWIZZLE_DEFINED(Vec3Proxy,3, xyz)
    SWIZZLE_DEFINED(Vec3Proxy,3, xzx)
    SWIZZLE_DEFINED(Vec3Proxy,3, xzy)
    SWIZZLE_DEFINED(Vec3Proxy,3, xzz)
    SWIZZLE_DEFINED(Vec3Proxy,3, yxx)
    SWIZZLE_DEFINED(Vec3Proxy,3, yxy)
    SWIZZLE_DEFINED(Vec3Proxy,3, yxz)
    SWIZZLE_DEFINED(Vec3Proxy,3, yyx)
    SWIZZLE_DEFINED(Vec3Proxy,3, yyy)
    SWIZZLE_DEFINED(Vec3Proxy,3, yyz)
    SWIZZLE_DEFINED(Vec3Proxy,3, yzx)
    SWIZZLE_DEFINED(Vec3Proxy,3, yzy)
    SWIZZLE_DEFINED(Vec3Proxy,3, yzz)
    SWIZZLE_DEFINED(Vec3Proxy,3, zxx)
    SWIZZLE_DEFINED(Vec3Proxy,3, zxy)
    SWIZZLE_DEFINED(Vec3Proxy,3, zxz)
    SWIZZLE_DEFINED(Vec3Proxy,3, zyx)
    SWIZZLE_DEFINED(Vec3Proxy,3, zyy)
    SWIZZLE_DEFINED(Vec3Proxy,3, zyz)
    SWIZZLE_DEFINED(Vec3Proxy,3, zzx)
    SWIZZLE_DEFINED(Vec3Proxy,3, zzy)
    SWIZZLE_DEFINED(Vec3Proxy,3, zzz)

    template<typename T>
    struct Vec4Proxy : Vec3Proxy<T>
    {
        static constexpr uint32_t dimension = 4;
        VariateProxy<T> w;

        SWIZZLE_DECLARE(2, xw)
        SWIZZLE_DECLARE(2, yw)
        SWIZZLE_DECLARE(2, zw)
        SWIZZLE_DECLARE(2, wx)
        SWIZZLE_DECLARE(2, wy)
        SWIZZLE_DECLARE(2, wz)

        SWIZZLE_DECLARE(2, ww)

        SWIZZLE_DECLARE(3, wxx)
        SWIZZLE_DECLARE(3, wxy)
        SWIZZLE_DECLARE(3, wxz)
        SWIZZLE_DECLARE(3, wyx)
        SWIZZLE_DECLARE(3, wyy)
        SWIZZLE_DECLARE(3, wyz)
        SWIZZLE_DECLARE(3, wzx)
        SWIZZLE_DECLARE(3, wzy)
        SWIZZLE_DECLARE(3, wzz)

        SWIZZLE_DECLARE(3, xxw)
        SWIZZLE_DECLARE(3, xyw)
        SWIZZLE_DECLARE(3, xzw)
        SWIZZLE_DECLARE(3, yxw)
        SWIZZLE_DECLARE(3, yyw)
        SWIZZLE_DECLARE(3, yzw)
        SWIZZLE_DECLARE(3, zxw)
        SWIZZLE_DECLARE(3, zyw)
        SWIZZLE_DECLARE(3, zzw)

        SWIZZLE_DECLARE(3, xwx)
        SWIZZLE_DECLARE(3, xwy)
        SWIZZLE_DECLARE(3, xwz)
        SWIZZLE_DECLARE(3, ywx)
        SWIZZLE_DECLARE(3, ywy)
        SWIZZLE_DECLARE(3, ywz)
        SWIZZLE_DECLARE(3, zwx)
        SWIZZLE_DECLARE(3, zwy)
        SWIZZLE_DECLARE(3, zwz)

        SWIZZLE_DECLARE(3, wxw)
        SWIZZLE_DECLARE(3, wyw)
        SWIZZLE_DECLARE(3, wzw)

        SWIZZLE_DECLARE(3, xww)
        SWIZZLE_DECLARE(3, yww)
        SWIZZLE_DECLARE(3, zww)

        SWIZZLE_DECLARE(3, wwx)
        SWIZZLE_DECLARE(3, wwy)
        SWIZZLE_DECLARE(3, wwz)

        SWIZZLE_DECLARE(3, www)

        SWIZZLE_DECLARE(4, xxxx)
        SWIZZLE_DECLARE(4, xxxy)
        SWIZZLE_DECLARE(4, xxxz)
        SWIZZLE_DECLARE(4, xxxw)
        SWIZZLE_DECLARE(4, xxyx)
        SWIZZLE_DECLARE(4, xxyy)
        SWIZZLE_DECLARE(4, xxyz)
        SWIZZLE_DECLARE(4, xxyw)
        SWIZZLE_DECLARE(4, xxzx)
        SWIZZLE_DECLARE(4, xxzy)
        SWIZZLE_DECLARE(4, xxzz)
        SWIZZLE_DECLARE(4, xxzw)
        SWIZZLE_DECLARE(4, xxwx)
        SWIZZLE_DECLARE(4, xxwy)
        SWIZZLE_DECLARE(4, xxwz)
        SWIZZLE_DECLARE(4, xxww)
        SWIZZLE_DECLARE(4, xyxx)
        SWIZZLE_DECLARE(4, xyxy)
        SWIZZLE_DECLARE(4, xyxz)
        SWIZZLE_DECLARE(4, xyxw)
        SWIZZLE_DECLARE(4, xyyx)
        SWIZZLE_DECLARE(4, xyyy)
        SWIZZLE_DECLARE(4, xyyz)
        SWIZZLE_DECLARE(4, xyyw)
        SWIZZLE_DECLARE(4, xyzx)
        SWIZZLE_DECLARE(4, xyzy)
        SWIZZLE_DECLARE(4, xyzz)
        SWIZZLE_DECLARE(4, xyzw)
        SWIZZLE_DECLARE(4, xywx)
        SWIZZLE_DECLARE(4, xywy)
        SWIZZLE_DECLARE(4, xywz)
        SWIZZLE_DECLARE(4, xyww)
        SWIZZLE_DECLARE(4, xzxx)
        SWIZZLE_DECLARE(4, xzxy)
        SWIZZLE_DECLARE(4, xzxz)
        SWIZZLE_DECLARE(4, xzxw)
        SWIZZLE_DECLARE(4, xzyx)
        SWIZZLE_DECLARE(4, xzyy)
        SWIZZLE_DECLARE(4, xzyz)
        SWIZZLE_DECLARE(4, xzyw)
        SWIZZLE_DECLARE(4, xzzx)
        SWIZZLE_DECLARE(4, xzzy)
        SWIZZLE_DECLARE(4, xzzz)
        SWIZZLE_DECLARE(4, xzzw)
        SWIZZLE_DECLARE(4, xzwx)
        SWIZZLE_DECLARE(4, xzwy)
        SWIZZLE_DECLARE(4, xzwz)
        SWIZZLE_DECLARE(4, xzww)
        SWIZZLE_DECLARE(4, xwxx)
        SWIZZLE_DECLARE(4, xwxy)
        SWIZZLE_DECLARE(4, xwxz)
        SWIZZLE_DECLARE(4, xwxw)
        SWIZZLE_DECLARE(4, xwyx)
        SWIZZLE_DECLARE(4, xwyy)
        SWIZZLE_DECLARE(4, xwyz)
        SWIZZLE_DECLARE(4, xwyw)
        SWIZZLE_DECLARE(4, xwzx)
        SWIZZLE_DECLARE(4, xwzy)
        SWIZZLE_DECLARE(4, xwzz)
        SWIZZLE_DECLARE(4, xwzw)
        SWIZZLE_DECLARE(4, xwwx)
        SWIZZLE_DECLARE(4, xwwy)
        SWIZZLE_DECLARE(4, xwwz)
        SWIZZLE_DECLARE(4, xwww)

        SWIZZLE_DECLARE(4, yxxx)
        SWIZZLE_DECLARE(4, yxxy)
        SWIZZLE_DECLARE(4, yxxz)
        SWIZZLE_DECLARE(4, yxxw)
        SWIZZLE_DECLARE(4, yxyx)
        SWIZZLE_DECLARE(4, yxyy)
        SWIZZLE_DECLARE(4, yxyz)
        SWIZZLE_DECLARE(4, yxyw)
        SWIZZLE_DECLARE(4, yxzx)
        SWIZZLE_DECLARE(4, yxzy)
        SWIZZLE_DECLARE(4, yxzz)
        SWIZZLE_DECLARE(4, yxzw)
        SWIZZLE_DECLARE(4, yxwx)
        SWIZZLE_DECLARE(4, yxwy)
        SWIZZLE_DECLARE(4, yxwz)
        SWIZZLE_DECLARE(4, yxww)
        SWIZZLE_DECLARE(4, yyxx)
        SWIZZLE_DECLARE(4, yyxy)
        SWIZZLE_DECLARE(4, yyxz)
        SWIZZLE_DECLARE(4, yyxw)
        SWIZZLE_DECLARE(4, yyyx)
        SWIZZLE_DECLARE(4, yyyy)
        SWIZZLE_DECLARE(4, yyyz)
        SWIZZLE_DECLARE(4, yyyw)
        SWIZZLE_DECLARE(4, yyzx)
        SWIZZLE_DECLARE(4, yyzy)
        SWIZZLE_DECLARE(4, yyzz)
        SWIZZLE_DECLARE(4, yyzw)
        SWIZZLE_DECLARE(4, yywx)
        SWIZZLE_DECLARE(4, yywy)
        SWIZZLE_DECLARE(4, yywz)
        SWIZZLE_DECLARE(4, yyww)
        SWIZZLE_DECLARE(4, yzxx)
        SWIZZLE_DECLARE(4, yzxy)
        SWIZZLE_DECLARE(4, yzxz)
        SWIZZLE_DECLARE(4, yzxw)
        SWIZZLE_DECLARE(4, yzyx)
        SWIZZLE_DECLARE(4, yzyy)
        SWIZZLE_DECLARE(4, yzyz)
        SWIZZLE_DECLARE(4, yzyw)
        SWIZZLE_DECLARE(4, yzzx)
        SWIZZLE_DECLARE(4, yzzy)
        SWIZZLE_DECLARE(4, yzzz)
        SWIZZLE_DECLARE(4, yzzw)
        SWIZZLE_DECLARE(4, yzwx)
        SWIZZLE_DECLARE(4, yzwy)
        SWIZZLE_DECLARE(4, yzwz)
        SWIZZLE_DECLARE(4, yzww)
        SWIZZLE_DECLARE(4, ywxx)
        SWIZZLE_DECLARE(4, ywxy)
        SWIZZLE_DECLARE(4, ywxz)
        SWIZZLE_DECLARE(4, ywxw)
        SWIZZLE_DECLARE(4, ywyx)
        SWIZZLE_DECLARE(4, ywyy)
        SWIZZLE_DECLARE(4, ywyz)
        SWIZZLE_DECLARE(4, ywyw)
        SWIZZLE_DECLARE(4, ywzx)
        SWIZZLE_DECLARE(4, ywzy)
        SWIZZLE_DECLARE(4, ywzz)
        SWIZZLE_DECLARE(4, ywzw)
        SWIZZLE_DECLARE(4, ywwx)
        SWIZZLE_DECLARE(4, ywwy)
        SWIZZLE_DECLARE(4, ywwz)
        SWIZZLE_DECLARE(4, ywww)

        SWIZZLE_DECLARE(4, zxxx)
        SWIZZLE_DECLARE(4, zxxy)
        SWIZZLE_DECLARE(4, zxxz)
        SWIZZLE_DECLARE(4, zxxw)
        SWIZZLE_DECLARE(4, zxyx)
        SWIZZLE_DECLARE(4, zxyy)
        SWIZZLE_DECLARE(4, zxyz)
        SWIZZLE_DECLARE(4, zxyw)
        SWIZZLE_DECLARE(4, zxzx)
        SWIZZLE_DECLARE(4, zxzy)
        SWIZZLE_DECLARE(4, zxzz)
        SWIZZLE_DECLARE(4, zxzw)
        SWIZZLE_DECLARE(4, zxwx)
        SWIZZLE_DECLARE(4, zxwy)
        SWIZZLE_DECLARE(4, zxwz)
        SWIZZLE_DECLARE(4, zxww)
        SWIZZLE_DECLARE(4, zyxx)
        SWIZZLE_DECLARE(4, zyxy)
        SWIZZLE_DECLARE(4, zyxz)
        SWIZZLE_DECLARE(4, zyxw)
        SWIZZLE_DECLARE(4, zyyx)
        SWIZZLE_DECLARE(4, zyyy)
        SWIZZLE_DECLARE(4, zyyz)
        SWIZZLE_DECLARE(4, zyyw)
        SWIZZLE_DECLARE(4, zyzx)
        SWIZZLE_DECLARE(4, zyzy)
        SWIZZLE_DECLARE(4, zyzz)
        SWIZZLE_DECLARE(4, zyzw)
        SWIZZLE_DECLARE(4, zywx)
        SWIZZLE_DECLARE(4, zywy)
        SWIZZLE_DECLARE(4, zywz)
        SWIZZLE_DECLARE(4, zyww)
        SWIZZLE_DECLARE(4, zzxx)
        SWIZZLE_DECLARE(4, zzxy)
        SWIZZLE_DECLARE(4, zzxz)
        SWIZZLE_DECLARE(4, zzxw)
        SWIZZLE_DECLARE(4, zzyx)
        SWIZZLE_DECLARE(4, zzyy)
        SWIZZLE_DECLARE(4, zzyz)
        SWIZZLE_DECLARE(4, zzyw)
        SWIZZLE_DECLARE(4, zzzx)
        SWIZZLE_DECLARE(4, zzzy)
        SWIZZLE_DECLARE(4, zzzz)
        SWIZZLE_DECLARE(4, zzzw)
        SWIZZLE_DECLARE(4, zzwx)
        SWIZZLE_DECLARE(4, zzwy)
        SWIZZLE_DECLARE(4, zzwz)
        SWIZZLE_DECLARE(4, zzww)
        SWIZZLE_DECLARE(4, zwxx)
        SWIZZLE_DECLARE(4, zwxy)
        SWIZZLE_DECLARE(4, zwxz)
        SWIZZLE_DECLARE(4, zwxw)
        SWIZZLE_DECLARE(4, zwyx)
        SWIZZLE_DECLARE(4, zwyy)
        SWIZZLE_DECLARE(4, zwyz)
        SWIZZLE_DECLARE(4, zwyw)
        SWIZZLE_DECLARE(4, zwzx)
        SWIZZLE_DECLARE(4, zwzy)
        SWIZZLE_DECLARE(4, zwzz)
        SWIZZLE_DECLARE(4, zwzw)
        SWIZZLE_DECLARE(4, zwwx)
        SWIZZLE_DECLARE(4, zwwy)
        SWIZZLE_DECLARE(4, zwwz)
        SWIZZLE_DECLARE(4, zwww)

        SWIZZLE_DECLARE(4, wxxx)
        SWIZZLE_DECLARE(4, wxxy)
        SWIZZLE_DECLARE(4, wxxz)
        SWIZZLE_DECLARE(4, wxxw)
        SWIZZLE_DECLARE(4, wxyx)
        SWIZZLE_DECLARE(4, wxyy)
        SWIZZLE_DECLARE(4, wxyz)
        SWIZZLE_DECLARE(4, wxyw)
        SWIZZLE_DECLARE(4, wxzx)
        SWIZZLE_DECLARE(4, wxzy)
        SWIZZLE_DECLARE(4, wxzz)
        SWIZZLE_DECLARE(4, wxzw)
        SWIZZLE_DECLARE(4, wxwx)
        SWIZZLE_DECLARE(4, wxwy)
        SWIZZLE_DECLARE(4, wxwz)
        SWIZZLE_DECLARE(4, wxww)
        SWIZZLE_DECLARE(4, wyxx)
        SWIZZLE_DECLARE(4, wyxy)
        SWIZZLE_DECLARE(4, wyxz)
        SWIZZLE_DECLARE(4, wyxw)
        SWIZZLE_DECLARE(4, wyyx)
        SWIZZLE_DECLARE(4, wyyy)
        SWIZZLE_DECLARE(4, wyyz)
        SWIZZLE_DECLARE(4, wyyw)
        SWIZZLE_DECLARE(4, wyzx)
        SWIZZLE_DECLARE(4, wyzy)
        SWIZZLE_DECLARE(4, wyzz)
        SWIZZLE_DECLARE(4, wyzw)
        SWIZZLE_DECLARE(4, wywx)
        SWIZZLE_DECLARE(4, wywy)
        SWIZZLE_DECLARE(4, wywz)
        SWIZZLE_DECLARE(4, wyww)
        SWIZZLE_DECLARE(4, wzxx)
        SWIZZLE_DECLARE(4, wzxy)
        SWIZZLE_DECLARE(4, wzxz)
        SWIZZLE_DECLARE(4, wzxw)
        SWIZZLE_DECLARE(4, wzyx)
        SWIZZLE_DECLARE(4, wzyy)
        SWIZZLE_DECLARE(4, wzyz)
        SWIZZLE_DECLARE(4, wzyw)
        SWIZZLE_DECLARE(4, wzzx)
        SWIZZLE_DECLARE(4, wzzy)
        SWIZZLE_DECLARE(4, wzzz)
        SWIZZLE_DECLARE(4, wzzw)
        SWIZZLE_DECLARE(4, wzwx)
        SWIZZLE_DECLARE(4, wzwy)
        SWIZZLE_DECLARE(4, wzwz)
        SWIZZLE_DECLARE(4, wzww)
        SWIZZLE_DECLARE(4, wwxx)
        SWIZZLE_DECLARE(4, wwxy)
        SWIZZLE_DECLARE(4, wwxz)
        SWIZZLE_DECLARE(4, wwxw)
        SWIZZLE_DECLARE(4, wwyx)
        SWIZZLE_DECLARE(4, wwyy)
        SWIZZLE_DECLARE(4, wwyz)
        SWIZZLE_DECLARE(4, wwyw)
        SWIZZLE_DECLARE(4, wwzx)
        SWIZZLE_DECLARE(4, wwzy)
        SWIZZLE_DECLARE(4, wwzz)
        SWIZZLE_DECLARE(4, wwzw)
        SWIZZLE_DECLARE(4, wwwx)
        SWIZZLE_DECLARE(4, wwwy)
        SWIZZLE_DECLARE(4, wwwz)
        SWIZZLE_DECLARE(4, wwww)
    };

    SWIZZLE_DEFINED(Vec4Proxy,2, xw)
    SWIZZLE_DEFINED(Vec4Proxy,2, yw)
    SWIZZLE_DEFINED(Vec4Proxy,2, zw)
    SWIZZLE_DEFINED(Vec4Proxy,2, wx)
    SWIZZLE_DEFINED(Vec4Proxy,2, wy)
    SWIZZLE_DEFINED(Vec4Proxy,2, wz)

    SWIZZLE_DEFINED(Vec4Proxy,2, ww)

    SWIZZLE_DEFINED(Vec4Proxy,3, wxx)
    SWIZZLE_DEFINED(Vec4Proxy,3, wxy)
    SWIZZLE_DEFINED(Vec4Proxy,3, wxz)
    SWIZZLE_DEFINED(Vec4Proxy,3, wyx)
    SWIZZLE_DEFINED(Vec4Proxy,3, wyy)
    SWIZZLE_DEFINED(Vec4Proxy,3, wyz)
    SWIZZLE_DEFINED(Vec4Proxy,3, wzx)
    SWIZZLE_DEFINED(Vec4Proxy,3, wzy)
    SWIZZLE_DEFINED(Vec4Proxy,3, wzz)

    SWIZZLE_DEFINED(Vec4Proxy,3, xxw)
    SWIZZLE_DEFINED(Vec4Proxy,3, xyw)
    SWIZZLE_DEFINED(Vec4Proxy,3, xzw)
    SWIZZLE_DEFINED(Vec4Proxy,3, yxw)
    SWIZZLE_DEFINED(Vec4Proxy,3, yyw)
    SWIZZLE_DEFINED(Vec4Proxy,3, yzw)
    SWIZZLE_DEFINED(Vec4Proxy,3, zxw)
    SWIZZLE_DEFINED(Vec4Proxy,3, zyw)
    SWIZZLE_DEFINED(Vec4Proxy,3, zzw)

    SWIZZLE_DEFINED(Vec4Proxy,3, xwx)
    SWIZZLE_DEFINED(Vec4Proxy,3, xwy)
    SWIZZLE_DEFINED(Vec4Proxy,3, xwz)
    SWIZZLE_DEFINED(Vec4Proxy,3, ywx)
    SWIZZLE_DEFINED(Vec4Proxy,3, ywy)
    SWIZZLE_DEFINED(Vec4Proxy,3, ywz)
    SWIZZLE_DEFINED(Vec4Proxy,3, zwx)
    SWIZZLE_DEFINED(Vec4Proxy,3, zwy)
    SWIZZLE_DEFINED(Vec4Proxy,3, zwz)

    SWIZZLE_DEFINED(Vec4Proxy,3, wxw)
    SWIZZLE_DEFINED(Vec4Proxy,3, wyw)
    SWIZZLE_DEFINED(Vec4Proxy,3, wzw)

    SWIZZLE_DEFINED(Vec4Proxy,3, xww)
    SWIZZLE_DEFINED(Vec4Proxy,3, yww)
    SWIZZLE_DEFINED(Vec4Proxy,3, zww)

    SWIZZLE_DEFINED(Vec4Proxy,3, wwx)
    SWIZZLE_DEFINED(Vec4Proxy,3, wwy)
    SWIZZLE_DEFINED(Vec4Proxy,3, wwz)

    SWIZZLE_DEFINED(Vec4Proxy,3, www)

    SWIZZLE_DEFINED(Vec4Proxy,4, xxxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xxww)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xywx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xywy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xywz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xyww)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xzww)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, xwww)

    SWIZZLE_DEFINED(Vec4Proxy,4, yxxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yxww)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yywx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yywy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yywz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yyww)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, yzww)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, ywww)

    SWIZZLE_DEFINED(Vec4Proxy,4, zxxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zxww)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zywx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zywy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zywz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zyww)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zzww)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, zwww)

    SWIZZLE_DEFINED(Vec4Proxy,4, wxxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wxww)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wywx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wywy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wywz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wyww)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wzww)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwxx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwxy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwxz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwxw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwyx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwyy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwyz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwyw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwzx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwzy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwzz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwzw)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwwx)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwwy)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwwz)
    SWIZZLE_DEFINED(Vec4Proxy,4, wwww)

#undef SWIZZLE_DECLARE
#undef SWIZZLE_DEFINED

    template<typename T>
    struct IsVecProxy
    {
        static constexpr bool value = false;
    };

    template<typename T>
    struct IsVecProxy<Vec2Proxy<T>>
    {
        static constexpr bool value = true;
    };

    template<typename T>
    struct IsVecProxy<Vec3Proxy<T>>
    {
        static constexpr bool value = true;
    };

    template<typename T>
    struct IsVecProxy<Vec4Proxy<T>>
    {
        static constexpr bool value = true;
    };

    template<size_t N,typename T>
    struct VecProxy
    {

    };

    template<typename T>
    struct VecProxy<2,T>
    {
        using proxy_type = Vec2Proxy<T>;
    };

    template<typename T>
    struct VecProxy<3,T>
    {
        using proxy_type = Vec3Proxy<T>;
    };

    template<typename T>
    struct VecProxy<4,T>
    {
        using proxy_type = Vec4Proxy<T>;
    };

    template<typename T> requires ktm::is_vector_v<T>
    struct VecProxyMap
    {
        using proxy_type = typename VecProxy<ktm::vec_traits_len<T>,ktm::vec_traits_base_t<T>>::proxy_type;
    };
}